### ISSUE TITLE
Everything from BuyExecution is burned

### ISSUE THREAD

**Issue by dndll** [t3rn/xbi#46]
### Item Type

Bug

### Description

We must have some magic configured in integration tests because everything from the `BuyExecution` call is just being burned at the target. This needs to be tied against the weight of the call and not just burn everything or at the very least allow it to be claimable.

### Additional Information

Do `test::user_is_refunded_most_of_fees_on_target_fail` to see the events.

### Acceptance Criteria

bug

### What are the points assigned to this item?

None

### Is the issue ready?

- [ ] This issue is ready

**Comment by AwesomeIbex** [comment]
Most of work is [here](https://github.com/t3rn/xbi/tree/bug/buy-execution-dump), although the Pay prediction reared its head again
